#include <bits/stdc++.h>
using namespace std;

class p {
public:
int num;
string name;
string type;
int evolutionLevel;
p(int num, string name, string type) {
this->num = num;
this->name = name;
this->type = type;
}

p(int num, string name, string type, int evolutionLevel) {
this->num = num;
this->name = name;
this->type = type;
this->evolutionLevel = evolutionLevel;
}
};
vector<p> pokemons;

#define POKEMON_(NUMBER, NAME, TYPE) pokemons.push_back(p(NUMBER, NAME, TYPE))
#define POKEMON(NUMBER, NAME, TYPE, evolutionLEVEL) pokemons.push_back(p(NUMBER, NAME, TYPE, evolutionLEVEL))


int main() {

POKEMON(1, "Bulbasaur", "Grass Poison", 25);
POKEMON(2, "Ivysaur", "Grass Poison", 100);
POKEMON(3, "Venusaur", "Grass Poison", -1);
POKEMON(4, "Charmander", "Fire", 25);
POKEMON(5, "Charmeleon", "Fire", 100);
POKEMON(6, "Charizard", "Fire Flying", -1);
POKEMON(7, "Squirtle", "Water", 25);
POKEMON(8, "Wartortle", "Water", 100);
POKEMON(9, "Blastoise", "Water", -1);
POKEMON(10, "Caterpie", "Bug", 12);
POKEMON(11, "Metapod", "Bug", 50);
POKEMON(12, "Butterfree", "Bug Flying", -1);
POKEMON(13, "Weedle", "Bug Poison", 12);
POKEMON(14, "Kakuna", "Bug Poison", 50);
POKEMON(15, "Beedrill", "Bug Poison", -1);
POKEMON(16, "Pidgey", "Normal Flying", 12);
POKEMON(17, "Pidgeotto", "Normal Flying", 50);
POKEMON(18, "Pidgeot", "Normal Flying", -1);
POKEMON(19, "Rattata", "Normal", 25);
POKEMON(20, "Raticate", "Normal", -1);
POKEMON(21, "Spearow", "Normal Flying", 50);
POKEMON(22, "Fearow", "Normal Flying", -1);
POKEMON(23, "Ekans", "Poison", 50);
POKEMON(24, "Arbok", "Poison", -1);
POKEMON(25, "Pikachu", "Electric", 50);
POKEMON(26, "Raichu", "Electric", -1);
POKEMON(27, "Sandshrew", "Ground", 50);
POKEMON(28, "Sandslash", "Ground", -1);
POKEMON(29, "Nidoran♀", "Poison", 25);
POKEMON(30, "Nidorina", "Poison", 100);
POKEMON(31, "Nidoqueen", "Poison Ground", -1);
POKEMON(32, "Nidoran♂", "Poison", 25);
POKEMON(33, "Nidorino", "Poison", 100);
POKEMON(34, "Nidoking", "Poison Ground", -1);
POKEMON(35, "Clefairy", "Fairy", 50);
POKEMON(36, "Clefable", "Fairy", -1);
POKEMON(37, "Vulpix", "Fire", 50);
POKEMON(38, "Ninetales", "Fire", -1);
POKEMON(39, "Jigglypuff", "Normal Fairy", 50);
POKEMON(40, "Wigglytuff", "Normal Fairy", -1);
POKEMON(41, "Zubat", "Poison Flying", 50);
POKEMON(42, "Golbat", "Poison Flying", -1);
POKEMON(43, "Oddish", "Grass Poison", 25);
POKEMON(44, "Gloom", "Grass Poison", 100);
POKEMON(45, "Vileplume", "Grass Poison", -1);
POKEMON(46, "Paras", "Bug Grass", 50);
POKEMON(47, "Parasect", "Bug Grass", -1);
POKEMON(48, "Venonat", "Bug Poison", 50);
POKEMON(49, "Venomoth", "Bug Poison", -1);
POKEMON(50, "Diglett", "Ground", 50);
POKEMON(51, "Dugtrio", "Ground", -1);
POKEMON(52, "Meowth", "Normal", 50);
POKEMON(53, "Persian", "Normal", -1);
POKEMON(54, "Psyduck", "Water", 50);
POKEMON(55, "Golduck", "Water", -1);
POKEMON(56, "Mankey", "Fighting", 50);
POKEMON(57, "Primeape", "Fighting", -1);
POKEMON(58, "Growlithe", "Fire", 50);
POKEMON(59, "Arcanine", "Fire", -1);
POKEMON(60, "Poliwag", "Water", 25);
POKEMON(61, "Poliwhirl", "Water", 100);
POKEMON(62, "Poliwrath", "Water Fighting", -1);
POKEMON(63, "Abra", "Psychic", 25);
POKEMON(64, "Kadabra", "Psychic", 100);
POKEMON(65, "Alakazam", "Psychic", -1);
POKEMON(66, "Machop", "Fighting", 25);
POKEMON(67, "Machoke", "Fighting", 100);
POKEMON(68, "Machamp", "Fighting", -1);
POKEMON(69, "Bellsprout", "Grass Poison", 25);
POKEMON(70, "Weepinbell", "Grass Poison", 100);
POKEMON(71, "Victreebel", "Grass Poison", -1);
POKEMON(72, "Tentacool", "Water Poison", 50);
POKEMON(73, "Tentacruel", "Water Poison", -1);
POKEMON(74, "Geodude", "Rock Ground", 25);
POKEMON(75, "Graveler", "Rock Ground", 100);
POKEMON(76, "Golem", "Rock Ground", -1);
POKEMON(77, "Ponyta", "Fire", 50);
POKEMON(78, "Rapidash", "Fire", -1);
POKEMON(79, "Slowpoke", "Water Psychic", 50);
POKEMON(80, "Slowbro", "Water Psychic", -1);
POKEMON(81, "Magnemite", "Electric Steel", 50);
POKEMON(82, "Magneton", "Electric Steel", -1);
POKEMON(83, "Farfetch'd", "Normal Flying", -1);
POKEMON(84, "Doduo", "Normal Flying", 50);
POKEMON(85, "Dodrio", "Normal Flying", -1);
POKEMON(86, "Seel", "Water", 50);
POKEMON(87, "Dewgong", "Water Ice", -1);
POKEMON(88, "Grimer", "Poison", 50);
POKEMON(89, "Muk", "Poison", -1);
POKEMON(90, "Shellder", "Water", 50);
POKEMON(91, "Cloyster", "Water Ice", -1);
POKEMON(92, "Gastly", "Ghost Poison", 25);
POKEMON(93, "Haunter", "Ghost Poison", 100);
POKEMON(94, "Gengar", "Ghost Poison", -1);
POKEMON(95, "Onix", "Rock Ground", -1);
POKEMON(96, "Drowzee", "Psychic", 50);
POKEMON(97, "Hypno", "Psychic", -1);
POKEMON(98, "Krabby", "Water", 50);
POKEMON(99, "Kingler", "Water", -1);
POKEMON(100, "Voltorb", "Electric", 50);
POKEMON(101, "Electrode", "Electric", -1);
POKEMON(102, "Exeggcute", "Grass Psychic", 50);
POKEMON(103, "Exeggutor", "Grass Psychic", -1);
POKEMON(104, "Cubone", "Ground", 50);
POKEMON(105, "Marowak", "Ground", -1);
POKEMON(106, "Hitmonlee", "Fighting", -1);
POKEMON(107, "Hitmonchan", "Fighting", -1);
POKEMON(108, "Lickitung", "Normal", -1);
POKEMON(109, "Koffing", "Poison", 50);
POKEMON(110, "Weezing", "Poison", -1);
POKEMON(111, "Rhyhorn", "Ground Rock", 50);
POKEMON(112, "Rhydon", "Ground Rock", -1);
POKEMON(113, "Chansey", "Normal", -1);
POKEMON(114, "Tangela", "Grass", -1);
POKEMON(115, "Kangaskhan", "Normal", -1);
POKEMON(116, "Horsea", "Water", 50);
POKEMON(117, "Seadra", "Water", -1);
POKEMON(118, "Goldeen", "Water", 50);
POKEMON(119, "Seaking", "Water", -1);
POKEMON(120, "Staryu", "Water", 50);
POKEMON(121, "Starmie", "Water Psychic", -1);
POKEMON(122, "Mr. Mime", "Psychic Fairy", -1);
POKEMON(123, "Scyther", "Bug Flying", -1);
POKEMON(124, "Jynx", "Ice Psychic", -1);
POKEMON(125, "Electabuzz", "Electric", -1);
POKEMON(126, "Magmar", "Fire", -1);
POKEMON(127, "Pinsir", "Bug", -1);
POKEMON(128, "Tauros", "Normal", -1);
POKEMON(129, "Magikarp", "Water", 400);
POKEMON(130, "Gyarados", "Water Flying", -1);
POKEMON(131, "Lapras", "Water Ice", -1);
POKEMON(132, "Ditto", "Normal", -1);
POKEMON(133, "Eevee", "Normal", 25);
POKEMON(134, "Vaporeon", "Water", -1);
POKEMON(135, "Jolteon", "Electric", -1);
POKEMON(136, "Flareon", "Fire", -1);
POKEMON(137, "Porygon", "Normal", -1);
POKEMON(138, "Omanyte", "Rock Water", 50);
POKEMON(139, "Omastar", "Rock Water", -1);
POKEMON(140, "Kabuto", "Rock Water", 50);
POKEMON(141, "Kabutops", "Rock Water", -1);
POKEMON(142, "Aerodactyl", "Rock Flying", -1);
POKEMON(143, "Snorlax", "Normal", -1);
POKEMON(144, "Articuno", "Ice Flying", -1);
POKEMON(145, "Zapdos", "Electric Flying", -1);
POKEMON(146, "Moltres", "Fire Flying", -1);
POKEMON(147, "Dratini", "Dragon", 25);
POKEMON(148, "Dragonair", "Dragon", 100);
POKEMON(149, "Dragonite", "Dragon Flying", -1);
POKEMON(150, "Mewtwo", "Psychic", -1);
POKEMON(151, "Mew", "Psychic", -1);


POKEMON_(151, "Chikorita", "Grass");
POKEMON_(152, "Bayleef", "Grass");
POKEMON_(153, "Meganium", "Grass");
POKEMON_(154, "Cyndaquil", "Fire");
POKEMON_(155, "Quilava", "Fire");
POKEMON_(156, "Typhlosion", "Fire");
POKEMON_(157, "Totodile", "Water");
POKEMON_(158, "Croconaw", "Water");
POKEMON_(159, "Feraligatr", "Water");
POKEMON_(160, "Sentret", "Normal");
POKEMON_(161, "Furret", "Normal");
POKEMON_(162, "Hoothoot", "Normal Flying");
POKEMON_(163, "Noctowl", "Normal Flying");
POKEMON_(164, "Ledyba", "Bug Flying");
POKEMON_(165, "Ledian", "Bug Flying");
POKEMON_(166, "Spinarak", "Bug Poison");
POKEMON_(167, "Ariados", "Bug Poison");
POKEMON_(168, "Crobat", "Poison Flying");
POKEMON_(169, "Chinchou", "Water Electric");
POKEMON_(170, "Lanturn", "Water Electric");
POKEMON_(171, "Pichu", "Electric");
POKEMON_(172, "Cleffa", "Fairy");
POKEMON_(173, "Igglybuff", "Normal Fairy");
POKEMON_(174, "Togepi", "Fairy");
POKEMON_(175, "Togetic", "Fairy Flying");
POKEMON_(176, "Natu", "Psychic Flying");
POKEMON_(177, "Xatu", "Psychic Flying");
POKEMON_(178, "Mareep", "Electric");
POKEMON_(179, "Flaaffy", "Electric");
POKEMON_(180, "Ampharos", "Electric");
POKEMON_(181, "Bellossom", "Grass");
POKEMON_(182, "Marill", "Water Fairy");
POKEMON_(183, "Azumarill", "Water Fairy");
POKEMON_(184, "Sudowoodo", "Rock");
POKEMON_(185, "Politoed", "Water");
POKEMON_(186, "Hoppip", "Grass Flying");
POKEMON_(187, "Skiploom", "Grass Flying");
POKEMON_(188, "Jumpluff", "Grass Flying");
POKEMON_(189, "Aipom", "Normal");
POKEMON_(190, "Sunkern", "Grass");
POKEMON_(191, "Sunflora", "Grass");
POKEMON_(192, "Yanma", "Bug Flying");
POKEMON_(193, "Wooper", "Water Ground");
POKEMON_(194, "Quagsire", "Water Ground");
POKEMON_(195, "Espeon", "Psychic");
POKEMON_(196, "Umbreon", "Dark");
POKEMON_(197, "Murkrow", "Dark Flying");
POKEMON_(198, "Slowking", "Water Psychic");
POKEMON_(199, "Misdreavus", "Ghost");
POKEMON_(200, "Unown", "Psychic");
POKEMON_(201, "Wobbuffet", "Psychic");
POKEMON_(202, "Girafarig", "Normal Psychic");
POKEMON_(203, "Pineco", "Bug");
POKEMON_(204, "Forretress", "Bug Steel");
POKEMON_(205, "Dunsparce", "Normal");
POKEMON_(206, "Gligar", "Ground Flying");
POKEMON_(207, "Steelix", "Steel Ground");
POKEMON_(208, "Snubbull", "Fairy");
POKEMON_(209, "Granbull", "Fairy");
POKEMON_(210, "Qwilfish", "Water Poison");
POKEMON_(211, "Scizor", "Bug Steel");
POKEMON_(212, "Shuckle", "Bug Rock");
POKEMON_(213, "Heracross", "Bug Fighting");
POKEMON_(214, "Sneasel", "Dark Ice");
POKEMON_(215, "Teddiursa", "Normal");
POKEMON_(216, "Ursaring", "Normal");
POKEMON_(217, "Slugma", "Fire");
POKEMON_(218, "Magcargo", "Fire Rock");
POKEMON_(219, "Swinub", "Ice Ground");
POKEMON_(220, "Piloswine", "Ice Ground");
POKEMON_(221, "Corsola", "Water Rock");
POKEMON_(222, "Remoraid", "Water");
POKEMON_(223, "Octillery", "Water");
POKEMON_(224, "Delibird", "Ice Flying");
POKEMON_(225, "Mantine", "Water Flying");
POKEMON_(226, "Skarmory", "Steel Flying");
POKEMON_(227, "Houndour", "Dark Fire");
POKEMON_(228, "Houndoom", "Dark Fire");
POKEMON_(229, "Kingdra", "Water Dragon");
POKEMON_(230, "Phanpy", "Ground");
POKEMON_(231, "Donphan", "Ground");
POKEMON_(232, "Porygon2", "Normal");
POKEMON_(233, "Stantler", "Normal");
POKEMON_(234, "Smeargle", "Normal");
POKEMON_(235, "Tyrogue", "Fighting");
POKEMON_(236, "Hitmontop", "Fighting");
POKEMON_(237, "Smoochum", "Ice Psychic");
POKEMON_(238, "Elekid", "Electric");
POKEMON_(239, "Magby", "Fire");
POKEMON_(240, "Miltank", "Normal");
POKEMON_(241, "Blissey", "Normal");
POKEMON_(242, "Raikou", "Electric");
POKEMON_(243, "Entei", "Fire");
POKEMON_(244, "Suicune", "Water");
POKEMON_(245, "Larvitar", "Rock Ground");
POKEMON_(246, "Pupitar", "Rock Ground");
POKEMON_(247, "Tyranitar", "Rock Dark");
POKEMON_(248, "Lugia", "Psychic Flying");
POKEMON_(249, "Ho-oh", "Fire Flying");
POKEMON_(250, "Celebi", "Psychic Grass");
POKEMON_(251, "Treecko", "Grass");
POKEMON_(252, "Grovyle", "Grass");
POKEMON_(253, "Sceptile", "Grass");
POKEMON_(254, "Torchic", "Fire");
POKEMON_(255, "Combusken", "Fire Fighting");
POKEMON_(256, "Blaziken", "Fire Fighting");
POKEMON_(257, "Mudkip", "Water");
POKEMON_(258, "Marshtomp", "Water Ground");
POKEMON_(259, "Swampert", "Water Ground");
POKEMON_(260, "Poochyena", "Dark");
POKEMON_(261, "Mightyena", "Dark");
POKEMON_(262, "Zigzagoon", "Normal");
POKEMON_(263, "Linoone", "Normal");
POKEMON_(264, "Wurmple", "Bug");
POKEMON_(265, "Silcoon", "Bug");
POKEMON_(266, "Beautifly", "Bug Flying");
POKEMON_(267, "Cascoon", "Bug");
POKEMON_(268, "Dustox", "Bug Poison");
POKEMON_(269, "Lotad", "Water Grass");
POKEMON_(270, "Lombre", "Water Grass");
POKEMON_(271, "Ludicolo", "Water Grass");
POKEMON_(272, "Seedot", "Grass");
POKEMON_(273, "Nuzleaf", "Grass Dark");
POKEMON_(274, "Shiftry", "Grass Dark");
POKEMON_(275, "Taillow", "Normal Flying");
POKEMON_(276, "Swellow", "Normal Flying");
POKEMON_(277, "Wingull", "Water Flying");
POKEMON_(278, "Pelipper", "Water Flying");
POKEMON_(279, "Ralts", "Psychic Fairy");
POKEMON_(280, "Kirlia", "Psychic Fairy");
POKEMON_(281, "Gardevoir", "Psychic Fairy");
POKEMON_(282, "Surskit", "Bug Water");
POKEMON_(283, "Masquerain", "Bug Flying");
POKEMON_(284, "Shroomish", "Grass");
POKEMON_(285, "Breloom", "Grass Fighting");
POKEMON_(286, "Slakoth", "Normal");
POKEMON_(287, "Vigoroth", "Normal");
POKEMON_(288, "Slaking", "Normal");
POKEMON_(289, "Nincada", "Bug Ground");
POKEMON_(290, "Ninjask", "Bug Flying");
POKEMON_(291, "Shedinja", "Bug Ghost");
POKEMON_(292, "Whismur", "Normal");
POKEMON_(293, "Loudred", "Normal");
POKEMON_(294, "Exploud", "Normal");
POKEMON_(295, "Makuhita", "Fighting");
POKEMON_(296, "Hariyama", "Fighting");
POKEMON_(297, "Azurill", "Normal Fairy");
POKEMON_(298, "Nosepass", "Rock");
POKEMON_(299, "Skitty", "Normal");
POKEMON_(300, "Delcatty", "Normal");
POKEMON_(301, "Sableye", "Dark Ghost");
POKEMON_(302, "Mawile", "Steel Fairy");
POKEMON_(303, "Aron", "Steel Rock");
POKEMON_(304, "Lairon", "Steel Rock");
POKEMON_(305, "Aggron", "Steel Rock");
POKEMON_(306, "Meditite", "Fighting Psychic");
POKEMON_(307, "Medicham", "Fighting Psychic");
POKEMON_(308, "Electrike", "Electric");
POKEMON_(309, "Manectric", "Electric");
POKEMON_(310, "Plusle", "Electric");
POKEMON_(311, "Minun", "Electric");
POKEMON_(312, "Volbeat", "Bug");
POKEMON_(313, "Illumise", "Bug");
POKEMON_(314, "Roselia", "Grass Poison");
POKEMON_(315, "Gulpin", "Poison");
POKEMON_(316, "Swalot", "Poison");
POKEMON_(317, "Carvanha", "Water Dark");
POKEMON_(318, "Sharpedo", "Water Dark");
POKEMON_(319, "Wailmer", "Water");
POKEMON_(320, "Wailord", "Water");
POKEMON_(321, "Numel", "Fire Ground");
POKEMON_(322, "Camerupt", "Fire Ground");
POKEMON_(323, "Torkoal", "Fire");
POKEMON_(324, "Spoink", "Psychic");
POKEMON_(325, "Grumpig", "Psychic");
POKEMON_(326, "Spinda", "Normal");
POKEMON_(327, "Trapinch", "Ground");
POKEMON_(328, "Vibrava", "Ground Dragon");
POKEMON_(329, "Flygon", "Ground Dragon");
POKEMON_(330, "Cacnea", "Grass");
POKEMON_(331, "Cacturne", "Grass Dark");
POKEMON_(332, "Swablu", "Normal Flying");
POKEMON_(333, "Altaria", "Dragon Flying");
POKEMON_(334, "Zangoose", "Normal");
POKEMON_(335, "Seviper", "Poison");
POKEMON_(336, "Lunatone", "Rock Psychic");
POKEMON_(337, "Solrock", "Rock Psychic");
POKEMON_(338, "Barboach", "Water Ground");
POKEMON_(339, "Whiscash", "Water Ground");
POKEMON_(340, "Corphish", "Water");
POKEMON_(341, "Crawdaunt", "Water Dark");
POKEMON_(342, "Baltoy", "Ground Psychic");
POKEMON_(343, "Claydol", "Ground Psychic");
POKEMON_(344, "Lileep", "Rock Grass");
POKEMON_(345, "Cradily", "Rock Grass");
POKEMON_(346, "Anorith", "Rock Bug");
POKEMON_(347, "Armaldo", "Rock Bug");
POKEMON_(348, "Feebas", "Water");
POKEMON_(349, "Milotic", "Water");
POKEMON_(350, "Castform", "Normal");
POKEMON_(351, "Kecleon", "Normal");
POKEMON_(352, "Shuppet", "Ghost");
POKEMON_(353, "Banette", "Ghost");
POKEMON_(354, "Duskull", "Ghost");
POKEMON_(355, "Dusclops", "Ghost");
POKEMON_(356, "Tropius", "Grass Flying");
POKEMON_(357, "Chimecho", "Psychic");
POKEMON_(358, "Absol", "Dark");
POKEMON_(359, "Wynaut", "Psychic");
POKEMON_(360, "Snorunt", "Ice");
POKEMON_(361, "Glalie", "Ice");
POKEMON_(362, "Spheal", "Ice Water");
POKEMON_(363, "Sealeo", "Ice Water");
POKEMON_(364, "Walrein", "Ice Water");
POKEMON_(365, "Clamperl", "Water");
POKEMON_(366, "Huntail", "Water");
POKEMON_(367, "Gorebyss", "Water");
POKEMON_(368, "Relicanth", "Water Rock");
POKEMON_(369, "Luvdisc", "Water");
POKEMON_(370, "Bagon", "Dragon");
POKEMON_(371, "Shelgon", "Dragon");
POKEMON_(372, "Salamence", "Dragon Flying");
POKEMON_(373, "Beldum", "Steel Psychic");
POKEMON_(374, "Metang", "Steel Psychic");
POKEMON_(375, "Metagross", "Steel Psychic");
POKEMON_(376, "Regirock", "Rock");
POKEMON_(377, "Regice", "Ice");
POKEMON_(378, "Registeel", "Steel");
POKEMON_(379, "Latias", "Dragon Psychic");
POKEMON_(380, "Latios", "Dragon Psychic");
POKEMON_(381, "Kyogre", "Water");
POKEMON_(382, "Groudon", "Ground");
POKEMON_(383, "Rayquaza", "Dragon Flying");
POKEMON_(384, "Jirachi", "Steel Psychic");
POKEMON_(385, "Deoxys", "Psychic");
POKEMON_(386, "Turtwig", "Grass");
POKEMON_(387, "Grotle", "Grass");
POKEMON_(388, "Torterra", "Grass Ground");
POKEMON_(389, "Chimchar", "Fire");
POKEMON_(390, "Monferno", "Fire Fighting");
POKEMON_(391, "Infernape", "Fire Fighting");
POKEMON_(392, "Piplup", "Water");
POKEMON_(393, "Prinplup", "Water");
POKEMON_(394, "Empoleon", "Water Steel");
POKEMON_(395, "Starly", "Normal Flying");
POKEMON_(396, "Staravia", "Normal Flying");
POKEMON_(397, "Staraptor", "Normal Flying");
POKEMON_(398, "Bidoof", "Normal");
POKEMON_(399, "Bibarel", "Normal Water");
POKEMON_(400, "Kricketot", "Bug");
POKEMON_(401, "Kricketune", "Bug");
POKEMON_(402, "Shinx", "Electric");
POKEMON_(403, "Luxio", "Electric");
POKEMON_(404, "Luxray", "Electric");
POKEMON_(405, "Budew", "Grass Poison");
POKEMON_(406, "Roserade", "Grass Poison");
POKEMON_(407, "Cranidos", "Rock");
POKEMON_(408, "Rampardos", "Rock");
POKEMON_(409, "Shieldon", "Rock Steel");
POKEMON_(410, "Bastiodon", "Rock Steel");
POKEMON_(411, "Burmy", "Bug");
POKEMON_(412, "Wormadam", "Bug Grass");
POKEMON_(413, "Mothim", "Bug Flying");
POKEMON_(414, "Combee", "Bug Flying");
POKEMON_(415, "Vespiquen", "Bug Flying");
POKEMON_(416, "Pachirisu", "Electric");
POKEMON_(417, "Buizel", "Water");
POKEMON_(418, "Floatzel", "Water");
POKEMON_(419, "Cherubi", "Grass");
POKEMON_(420, "Cherrim", "Grass");
POKEMON_(421, "Shellos", "Water");
POKEMON_(422, "Gastrodon", "Water Ground");
POKEMON_(423, "Ambipom", "Normal");
POKEMON_(424, "Drifloon", "Ghost Flying");
POKEMON_(425, "Drifblim", "Ghost Flying");
POKEMON_(426, "Buneary", "Normal");
POKEMON_(427, "Lopunny", "Normal");
POKEMON_(428, "Mismagius", "Ghost");
POKEMON_(429, "Honchkrow", "Dark Flying");
POKEMON_(430, "Glameow", "Normal");
POKEMON_(431, "Purugly", "Normal");
POKEMON_(432, "Chingling", "Psychic");
POKEMON_(433, "Stunky", "Poison Dark");
POKEMON_(434, "Skuntank", "Poison Dark");
POKEMON_(435, "Bronzor", "Steel Psychic");
POKEMON_(436, "Bronzong", "Steel Psychic");
POKEMON_(437, "Bonsly", "Rock");
POKEMON_(438, "Mime Jr.", "Psychic Fairy");
POKEMON_(439, "Happiny", "Normal");
POKEMON_(440, "Chatot", "Normal Flying");
POKEMON_(441, "Spiritomb", "Ghost Dark");
POKEMON_(442, "Gible", "Dragon Ground");
POKEMON_(443, "Gabite", "Dragon Ground");
POKEMON_(444, "Garchomp", "Dragon Ground");
POKEMON_(445, "Munchlax", "Normal");
POKEMON_(446, "Riolu", "Fighting");
POKEMON_(447, "Lucario", "Fighting Steel");
POKEMON_(448, "Hippopotas", "Ground");
POKEMON_(449, "Hippowdon", "Ground");
POKEMON_(450, "Skorupi", "Poison Bug");
POKEMON_(451, "Drapion", "Poison Dark");
POKEMON_(452, "Croagunk", "Poison Fighting");
POKEMON_(453, "Toxicroak", "Poison Fighting");
POKEMON_(454, "Carnivine", "Grass");
POKEMON_(455, "Finneon", "Water");
POKEMON_(456, "Lumineon", "Water");
POKEMON_(457, "Mantyke", "Water Flying");
POKEMON_(458, "Snover", "Grass Ice");
POKEMON_(459, "Abomasnow", "Grass Ice");
POKEMON_(460, "Weavile", "Dark Ice");
POKEMON_(461, "Magnezone", "Electric Steel");
POKEMON_(462, "Lickilicky", "Normal");
POKEMON_(463, "Rhyperior", "Ground Rock");
POKEMON_(464, "Tangrowth", "Grass");
POKEMON_(465, "Electivire", "Electric");
POKEMON_(466, "Magmortar", "Fire");
POKEMON_(467, "Togekiss", "Fairy Flying");
POKEMON_(468, "Yanmega", "Bug Flying");
POKEMON_(469, "Leafeon", "Grass");
POKEMON_(470, "Glaceon", "Ice");
POKEMON_(471, "Gliscor", "Ground Flying");
POKEMON_(472, "Mamoswine", "Ice Ground");
POKEMON_(473, "Porygon-Z", "Normal");
POKEMON_(474, "Gallade", "Psychic Fighting");
POKEMON_(475, "Probopass", "Rock Steel");
POKEMON_(476, "Dusknoir", "Ghost");
POKEMON_(477, "Froslass", "Ice Ghost");
POKEMON_(478, "Rotom", "Electric Ghost");
POKEMON_(479, "Uxie", "Psychic");
POKEMON_(480, "Mesprit", "Psychic");
POKEMON_(481, "Azelf", "Psychic");
POKEMON_(482, "Dialga", "Steel Dragon");
POKEMON_(483, "Palkia", "Water Dragon");
POKEMON_(484, "Heatran", "Fire Steel");
POKEMON_(485, "Regigigas", "Normal");
POKEMON_(486, "Giratina", "Ghost Dragon");
POKEMON_(487, "Cresselia", "Psychic");
POKEMON_(488, "Phione", "Water");
POKEMON_(489, "Manaphy", "Water");
POKEMON_(490, "Darkrai", "Dark");
POKEMON_(491, "Shaymin", "Grass");
POKEMON_(492, "Arceus", "Normal");
POKEMON_(493, "Victini", "Psychic Fire");
POKEMON_(494, "Snivy", "Grass");
POKEMON_(495, "Servine", "Grass");
POKEMON_(496, "Serperior", "Grass");
POKEMON_(497, "Tepig", "Fire");
POKEMON_(498, "Pignite", "Fire Fighting");
POKEMON_(499, "Emboar", "Fire Fighting");
POKEMON_(500, "Oshawott", "Water");
POKEMON_(501, "Dewott", "Water");
POKEMON_(502, "Samurott", "Water");
POKEMON_(503, "Patrat", "Normal");
POKEMON_(504, "Watchog", "Normal");
POKEMON_(505, "Lillipup", "Normal");
POKEMON_(506, "Herdier", "Normal");
POKEMON_(507, "Stoutland", "Normal");
POKEMON_(508, "Purrloin", "Dark");
POKEMON_(509, "Liepard", "Dark");
POKEMON_(510, "Pansage", "Grass");
POKEMON_(511, "Simisage", "Grass");
POKEMON_(512, "Pansear", "Fire");
POKEMON_(513, "Simisear", "Fire");
POKEMON_(514, "Panpour", "Water");
POKEMON_(515, "Simipour", "Water");
POKEMON_(516, "Munna", "Psychic");
POKEMON_(517, "Musharna", "Psychic");
POKEMON_(518, "Pidove", "Normal Flying");
POKEMON_(519, "Tranquill", "Normal Flying");
POKEMON_(520, "Unfezant", "Normal Flying");
POKEMON_(521, "Blitzle", "Electric");
POKEMON_(522, "Zebstrika", "Electric");
POKEMON_(523, "Roggenrola", "Rock");
POKEMON_(524, "Boldore", "Rock");
POKEMON_(525, "Gigalith", "Rock");
POKEMON_(526, "Woobat", "Psychic Flying");
POKEMON_(527, "Swoobat", "Psychic Flying");
POKEMON_(528, "Drilbur", "Ground");
POKEMON_(529, "Excadrill", "Ground Steel");
POKEMON_(530, "Audino", "Normal");
POKEMON_(531, "Timburr", "Fighting");
POKEMON_(532, "Gurdurr", "Fighting");
POKEMON_(533, "Conkeldurr", "Fighting");
POKEMON_(534, "Tympole", "Water");
POKEMON_(535, "Palpitoad", "Water Ground");
POKEMON_(536, "Seismitoad", "Water Ground");
POKEMON_(537, "Throh", "Fighting");
POKEMON_(538, "Sawk", "Fighting");
POKEMON_(539, "Sewaddle", "Bug Grass");
POKEMON_(540, "Swadloon", "Bug Grass");
POKEMON_(541, "Leavanny", "Bug Grass");
POKEMON_(542, "Venipede", "Bug Poison");
POKEMON_(543, "Whirlipede", "Bug Poison");
POKEMON_(544, "Scolipede", "Bug Poison");
POKEMON_(545, "Cottonee", "Grass Fairy");
POKEMON_(546, "Whimsicott", "Grass Fairy");
POKEMON_(547, "Petilil", "Grass");
POKEMON_(548, "Lilligant", "Grass");
POKEMON_(549, "Basculin", "Water");
POKEMON_(550, "Sandile", "Ground Dark");
POKEMON_(551, "Krokorok", "Ground Dark");
POKEMON_(552, "Krookodile", "Ground Dark");
POKEMON_(553, "Darumaka", "Fire");
POKEMON_(554, "Darmanitan", "Fire");
POKEMON_(555, "Maractus", "Grass");
POKEMON_(556, "Dwebble", "Bug Rock");
POKEMON_(557, "Crustle", "Bug Rock");
POKEMON_(558, "Scraggy", "Dark Fighting");
POKEMON_(559, "Scrafty", "Dark Fighting");
POKEMON_(560, "Sigilyph", "Psychic Flying");
POKEMON_(561, "Yamask", "Ghost");
POKEMON_(562, "Cofagrigus", "Ghost");
POKEMON_(563, "Tirtouga", "Water Rock");
POKEMON_(564, "Carracosta", "Water Rock");
POKEMON_(565, "Archen", "Rock Flying");
POKEMON_(566, "Archeops", "Rock Flying");
POKEMON_(567, "Trubbish", "Poison");
POKEMON_(568, "Garbodor", "Poison");
POKEMON_(569, "Zorua", "Dark");
POKEMON_(570, "Zoroark", "Dark");
POKEMON_(571, "Minccino", "Normal");
POKEMON_(572, "Cinccino", "Normal");
POKEMON_(573, "Gothita", "Psychic");
POKEMON_(574, "Gothorita", "Psychic");
POKEMON_(575, "Gothitelle", "Psychic");
POKEMON_(576, "Solosis", "Psychic");
POKEMON_(577, "Duosion", "Psychic");
POKEMON_(578, "Reuniclus", "Psychic");
POKEMON_(579, "Ducklett", "Water Flying");
POKEMON_(580, "Swanna", "Water Flying");
POKEMON_(581, "Vanillite", "Ice");
POKEMON_(582, "Vanillish", "Ice");
POKEMON_(583, "Vanilluxe", "Ice");
POKEMON_(584, "Deerling", "Normal Grass");
POKEMON_(585, "Sawsbuck", "Normal Grass");
POKEMON_(586, "Emolga", "Electric Flying");
POKEMON_(587, "Karrablast", "Bug");
POKEMON_(588, "Escavalier", "Bug Steel");
POKEMON_(589, "Foongus", "Grass Poison");
POKEMON_(590, "Amoonguss", "Grass Poison");
POKEMON_(591, "Frillish", "Water Ghost");
POKEMON_(592, "Jellicent", "Water Ghost");
POKEMON_(593, "Alomomola", "Water");
POKEMON_(594, "Joltik", "Bug Electric");
POKEMON_(595, "Galvantula", "Bug Electric");
POKEMON_(596, "Ferroseed", "Grass Steel");
POKEMON_(597, "Ferrothorn", "Grass Steel");
POKEMON_(598, "Klink", "Steel");
POKEMON_(599, "Klang", "Steel");
POKEMON_(600, "Klinklang", "Steel");
POKEMON_(601, "Tynamo", "Electric");
POKEMON_(602, "Eelektrik", "Electric");
POKEMON_(603, "Eelektross", "Electric");
POKEMON_(604, "Elgyem", "Psychic");
POKEMON_(605, "Beheeyem", "Psychic");
POKEMON_(606, "Litwick", "Ghost Fire");
POKEMON_(607, "Lampent", "Ghost Fire");
POKEMON_(608, "Chandelure", "Ghost Fire");
POKEMON_(609, "Axew", "Dragon");
POKEMON_(610, "Fraxure", "Dragon");
POKEMON_(611, "Haxorus", "Dragon");
POKEMON_(612, "Cubchoo", "Ice");
POKEMON_(613, "Beartic", "Ice");
POKEMON_(614, "Cryogonal", "Ice");
POKEMON_(615, "Shelmet", "Bug");
POKEMON_(616, "Accelgor", "Bug");
POKEMON_(617, "Stunfisk", "Electric Ground");
POKEMON_(618, "Mienfoo", "Fighting");
POKEMON_(619, "Mienshao", "Fighting");
POKEMON_(620, "Druddigon", "Dragon");
POKEMON_(621, "Golett", "Ground Ghost");
POKEMON_(622, "Golurk", "Ground Ghost");
POKEMON_(623, "Pawniard", "Dark Steel");
POKEMON_(624, "Bisharp", "Dark Steel");
POKEMON_(625, "Bouffalant", "Normal");
POKEMON_(626, "Rufflet", "Normal Flying");
POKEMON_(627, "Braviary", "Normal Flying");
POKEMON_(628, "Vullaby", "Dark Flying");
POKEMON_(629, "Mandibuzz", "Dark Flying");
POKEMON_(630, "Heatmor", "Fire");
POKEMON_(631, "Durant", "Bug Steel");
POKEMON_(632, "Deino", "Dark Dragon");
POKEMON_(633, "Zweilous", "Dark Dragon");
POKEMON_(634, "Hydreigon", "Dark Dragon");
POKEMON_(635, "Larvesta", "Bug Fire");
POKEMON_(636, "Volcarona", "Bug Fire");
POKEMON_(637, "Cobalion", "Steel Fighting");
POKEMON_(638, "Terrakion", "Rock Fighting");
POKEMON_(639, "Virizion", "Grass Fighting");
POKEMON_(640, "Tornadus", "Flying");
POKEMON_(641, "Thundurus", "Electric Flying");
POKEMON_(642, "Reshiram", "Dragon Fire");
POKEMON_(643, "Zekrom", "Dragon Electric");
POKEMON_(644, "Landorus", "Ground Flying");
POKEMON_(645, "Kyurem", "Dragon Ice");
POKEMON_(646, "Keldeo", "Water Fighting");
POKEMON_(647, "Meloetta", "Normal Psychic");
POKEMON_(648, "Genesect", "Bug Steel");
POKEMON_(649, "Chespin", "Grass");
POKEMON_(650, "Quilladin", "Grass");
POKEMON_(651, "Chesnaught", "Grass Fighting");
POKEMON_(652, "Fennekin", "Fire");
POKEMON_(653, "Braixen", "Fire");
POKEMON_(654, "Delphox", "Fire Psychic");
POKEMON_(655, "Froakie", "Water");
POKEMON_(656, "Frogadier", "Water");
POKEMON_(657, "Greninja", "Water Dark");
POKEMON_(658, "Bunnelby", "Normal");
POKEMON_(659, "Diggersby", "Normal Ground");
POKEMON_(660, "Fletchling", "Normal Flying");
POKEMON_(661, "Fletchinder", "Fire Flying");
POKEMON_(662, "Talonflame", "Fire Flying");
POKEMON_(663, "Scatterbug", "Bug");
POKEMON_(664, "Spewpa", "Bug");
POKEMON_(665, "Vivillon", "Bug Flying");
POKEMON_(666, "Litleo", "Fire Normal");
POKEMON_(667, "Pyroar", "Fire Normal");
POKEMON_(668, "Flabébé", "Fairy");
POKEMON_(669, "Floette", "Fairy");
POKEMON_(670, "Florges", "Fairy");
POKEMON_(671, "Skiddo", "Grass");
POKEMON_(672, "Gogoat", "Grass");
POKEMON_(673, "Pancham", "Fighting");
POKEMON_(674, "Pangoro", "Fighting Dark");
POKEMON_(675, "Furfrou", "Normal");
POKEMON_(676, "Espurr", "Psychic");
POKEMON_(677, "Meowstic", "Psychic");
POKEMON_(678, "Honedge", "Steel Ghost");
POKEMON_(679, "Doublade", "Steel Ghost");
POKEMON_(680, "Aegislash", "Steel Ghost");
POKEMON_(681, "Spritzee", "Fairy");
POKEMON_(682, "Aromatisse", "Fairy");
POKEMON_(683, "Swirlix", "Fairy");
POKEMON_(684, "Slurpuff", "Fairy");
POKEMON_(685, "Inkay", "Dark Psychic");
POKEMON_(686, "Malamar", "Dark Psychic");
POKEMON_(687, "Binacle", "Rock Water");
POKEMON_(688, "Barbaracle", "Rock Water");
POKEMON_(689, "Skrelp", "Poison Water");
POKEMON_(690, "Dragalge", "Poison Dragon");
POKEMON_(691, "Clauncher", "Water");
POKEMON_(692, "Clawitzer", "Water");
POKEMON_(693, "Helioptile", "Electric Normal");
POKEMON_(694, "Heliolisk", "Electric Normal");
POKEMON_(695, "Tyrunt", "Rock Dragon");
POKEMON_(696, "Tyrantrum", "Rock Dragon");
POKEMON_(697, "Amaura", "Rock Ice");
POKEMON_(698, "Aurorus", "Rock Ice");
POKEMON_(699, "Sylveon", "Fairy");
POKEMON_(700, "Hawlucha", "Fighting Flying");
POKEMON_(701, "Dedenne", "Electric Fairy");
POKEMON_(702, "Carbink", "Rock Fairy");
POKEMON_(703, "Goomy", "Dragon");
POKEMON_(704, "Sliggoo", "Dragon");
POKEMON_(705, "Goodra", "Dragon");
POKEMON_(706, "Klefki", "Steel Fairy");
POKEMON_(707, "Phantump", "Ghost Grass");
POKEMON_(708, "Trevenant", "Ghost Grass");
POKEMON_(709, "Pumpkaboo", "Ghost Grass");
POKEMON_(710, "Gourgeist", "Ghost Grass");
POKEMON_(711, "Bergmite", "Ice");
POKEMON_(712, "Avalugg", "Ice");
POKEMON_(713, "Noibat", "Flying Dragon");
POKEMON_(714, "Noivern", "Flying Dragon");
POKEMON_(715, "Xerneas", "Fairy");
POKEMON_(716, "Yveltal", "Dark Flying");
POKEMON_(717, "Zygarde", "Dragon Ground");
int n;
cin >> n;
n--;
cout << pokemons[n].evolutionLevel;
return 0;
}